# Generated by Django 5.2.6 on 2025-09-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cflows', '0002_add_mentions_to_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='current_step_entered_at',
            field=models.DateTimeField(blank=True, help_text='When this work item entered the current step', null=True),
        ),
    ]
