# Generated by Django 5.2.6 on 2025-09-18 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cflows', '0003_workitem_current_step_entered_at'),
        ('core', '0002_alter_team_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workflow',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workflow',
            name='parent_workflow',
            field=models.ForeignKey(blank=True, help_text='Parent workflow - leave empty for top-level workflows', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_workflows', to='cflows.workflow'),
        ),
        migrations.AlterUniqueTogether(
            name='workflow',
            unique_together={('organization', 'name', 'parent_workflow')},
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['organization', 'is_active'], name='cflows_work_organiz_0b5a49_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['parent_workflow'], name='cflows_work_parent__6ca43e_idx'),
        ),
    ]
