# Generated by Django 5.2.6 on 2025-09-18 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cflows', '0004_alter_workflow_unique_together_and_more'),
        ('core', '0002_alter_team_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItemFilterView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('workflow', models.CharField(blank=True, max_length=20)),
                ('assignee', models.CharField(blank=True, max_length=20)),
                ('priority', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('search', models.CharField(blank=True, max_length=200)),
                ('sort', models.CharField(default='-updated_at', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_work_item_filter_views', to='core.userprofile')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
