# Generated by Django 5.2.6 on 2025-09-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('organization', 'name', 'parent_team')},
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['parent_team'], name='core_team_parent__87e250_idx'),
        ),
    ]
