# Generated by Django 5.2.6 on 2025-09-10 20:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "integration_type",
                    models.CharField(
                        choices=[
                            ("slack", "Slack"),
                            ("teams", "Microsoft Teams"),
                            ("google", "Google Workspace"),
                            ("github", "GitHub"),
                            ("jira", "Jira"),
                            ("zapier", "Zapier"),
                            ("webhook", "Custom Webhook"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Custom name for this integration", max_length=200
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("error", "Error"),
                            ("pending", "Pending Configuration"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="Integration-specific configuration"
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(
                        blank=True, help_text="Webhook URL for receiving events"
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, help_text="Encrypted API key", max_length=500
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("send_notifications", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("sync_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["integration_type", "name"],
                "unique_together": {("organization", "integration_type", "name")},
            },
        ),
        migrations.CreateModel(
            name="IntegrationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("success", "Success"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("sync", "Sync"),
                            ("send", "Send"),
                            ("receive", "Receive"),
                            ("configure", "Configure"),
                            ("test", "Test"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("details", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="staff_panel.integration",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
