name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: mediap.settings
      DJANGO_SECRET_KEY: dummy
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
      DEBUG: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Django checks
        run: |
          python manage.py check --deploy --fail-level WARNING || true
          python manage.py makemigrations --check --dry-run
      - name: Build image
        run: docker build -t metatask:ci .